spring:
   profiles:
      active: 'prod'
   liquibase:
      changeLog: classpath:/db/master.xml
      
project:
   code: 'jproxy'
   name: 'JProxy'
   version: '2.6.4'

server:
   port: 8117
   servlet:
      context-path: /
   
mybatis-plus:
   mapper-locations: classpath:com/lckp/${project.code}/mapper/*.xml
   typeAliasesPackage: com.lckp.${project.code}.model
   check-config-location: true
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
      jdbc-type-for-null: 'null'
      auto-mapping-unknown-column-behavior: warning
   global-config:
      banner: false
      db-config:
         id-type: AUTO
         select-strategy: NOT_EMPTY
         insert-strategy: NOT_EMPTY
         update-strategy: NOT_EMPTY
         capital-mode: true
         logic-delete-value: 0
         logic-not-delete-value: 1

         